title: "Ruinan Zhao"
name: "Ruinan Zhao"
email: "ruinan.zhao@email.ucr.edu"
description: "Economics Ph.D. Candidate at UC Riverside â€” Labor, Education, Applied Micro, Public Policy."
url: "https://ruinan-zhao.github.io"
baseurl: ""

# Use Minimal Mistakes (AcademicPages is built on it)
remote_theme: "mmistakes/minimal-mistakes"

# Plugins allowed by GitHub Pages
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-include-cache

# Skin (color palette)
minimal_mistakes_skin: "default" # options: air, aqua, dark, dusk, neon, sunrise, etc.

# Author sidebar
author:
  name: "Ruinan Zhao"
  avatar: "profile.jpeg"
  bio: "Ph.D. Candidate in Economics, University of California, Riverside."
  location: "UC Riverside"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:ruinan.zhao@email.ucr.edu"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ruinan-zhao"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/ruinan-zhao-b07614388"

# Defaults so pages get the sidebar
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true



defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      classes: wide   # or "full" if you want edge-to-edge



sass:
  style: compressed
include:
  - assets/css      
