title: "Ruinan Zhao"
url: "https://ruinan-zhao.github.io"
baseurl: ""

# Use a built-in theme that GitHub Pages always supports
theme: jekyll-theme-cayman

markdown: kramdown
highlighter: rouge
permalink: /:title/
